services:
  gphotos-sync-profile2:
    build:
      context: /home/taki/Documents/GitHub/Gphoto_sync
    container_name: gphotos-sync-profile2
    restart: unless-stopped
    privileged: true
    volumes:
      - /home/taki/Documents/GitHub/Gphoto_sync/profile2:/tmp/gphotos-cdp
      - /home/taki/Documents/GitHub/Gphoto_sync/photos2:/download
    environment:
      - PUID=1000
      - PGID=1000
      - CRON_SCHEDULE=0 4 * * *
      - RUN_ON_STARTUP=true
      - LOGLEVEL=info
      - TZ=Europe/Rome
      - WORKER_COUNT=6
    networks:
      - gphotos-network

networks:
  gphotos-network:
    external: true
