services:
  gphotos-sync-profile1:
    image: gphotos-sync:latest
    container_name: gphotos-sync-profile1
    restart: unless-stopped
    privileged: true
    volumes:
      - /home/taki/Documents/GitHub/Gphoto_sync/profile1:/tmp/gphotos-cdp
      - /home/taki/Documents/GitHub/Gphoto_sync/photos1:/download
    environment:
      - PUID=1000
      - PGID=1000
      - CRON_SCHEDULE=0 3 * * *
      - RUN_ON_STARTUP=true
      - LOGLEVEL=info
      - TZ=Europe/Rome
      - WORKER_COUNT=6
    networks:
      - gphotos-network

networks:
  gphotos-network:
    external: true
